### ISSUE TITLE
vpn not work in LOS 17.1 due to missing kernel patches 

### ISSUE THREAD

**Issue by doofin** [LineageOS/android_kernel_oneplus_sm8150#1]
https://gitlab.com/LineageOS/issues/android/-/issues/2193

**Comment by luk1337** [comment]
except the mentioned patch is already there.

**Comment by doofin** [comment]
I searched around this repo and can't find flow.h mentioned in the link. I just flashed the newest build for my oneplus 7 pro and find v2ray VPN is not working. I am new to LOS development,would  you like to tell me how to debug such problems? 
thanks!

**Comment by luk1337** [comment]
https://github.com/LineageOS/android_kernel_oneplus_sm8150/commits/lineage-17.1/include/net/flow.h

**Comment by luk1337** [comment]
Also I have no idea how to debug anything vpn related.

**Comment by doofin** [comment]
It's time related issue.worked after fixing clock,thanks!
