### ISSUE TITLE
new build Stuck On Boot Animation

### ISSUE THREAD

**Issue by doofin** [LineageOS/android_kernel_oneplus_sm8150#2]
Hi,my OP 7 pro can't boot with both  lineage-17.1-20200913 and  lineage-17.1-20200906 both with system updater and adb sideload, but only  lineage-17.1-20200816 works.Is it required to do a complete fresh install with all data wiped out? Thanks!

**Comment by gwolf2u** [comment]
as per https://wiki.lineageos.org/bugreport-howto.html
please report issues to https://gitlab.com/LineageOS/issues
